import { GET_PRODUCT_LIST_RES } from "@/types/store/api";
import { PRODUCT_LIST } from "@/types/store/data";

import Head from "next/head";
import { lazy, Suspense } from "react";

const Loading = lazy(() => import("@/components/Loading"));
const ProductList = lazy(() => import("@/components/ProductList"));

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ||
  "https://nextjs-product-detail-seo.vercel.app";

function Store({ productList }: { productList: PRODUCT_LIST }) {
  return (
    <>
      <Head>
        <title>App - Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Product List</h1>

      <ProductList productList={productList} />
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${API_BASE_URL}/api/store/list`);
  const data: GET_PRODUCT_LIST_RES = await res.json();
  const productList = data.list;

  return {
    props: {
      productList,
    },
  };
}

export default Store;
