import { GET_PRODUCT_LIST_RES } from "@/types/store/api";

import Head from "next/head";
import { lazy, Suspense } from "react";

const Loading = lazy(() => import("@/components/Loading"));
const ProductList = lazy(() => import("@/components/ProductList"));

function Store({ list, total }: GET_PRODUCT_LIST_RES) {
  return (
    <>
      <Head>
        <title>App - Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Suspense fallback={<Loading />}>
        <h3>Total: {total}</h3>
        <ProductList productList={list} />
      </Suspense>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/store/list");
  const data = await res.json();
  const { list, total }: GET_PRODUCT_LIST_RES = data;

  return {
    props: {
      list,
      total,
    },
  };
}

export default Store;
